siteTitle="ATECH Environnement"
#linkPrefix = "/website"

#mailthisUrl = "http://mailthis.to/jcdelmas"
mailthisUrl = "http://mailthis.to/atech-environnement"

contactEmail = "contact@atech-environnement.com"
contactPhone = "06.30.22.57.48"

serviceFileUrl = "https://docs.google.com/spreadsheets/d/1nvxMIFUuNseQ44A1mGHt-n-Dap8DQ_K2wbcav_P6s_4/export?format=pdf&portrait=true&gridlines=false"