siteTitle="Atech environnement"
#linkPrefix = "/website"

#mailthisUrl = "http://mailthis.to/jcdelmas"
mailthisUrl = "http://mailthis.to/atech-environnement"

contactEmail = "contact@atech-environnement.com"
contactPhone = "06.30.22.57.48"
